### PR TITLE
Time pp join

### PR DESCRIPTION
**Pull request by xayang**

### CODE REVIEW

**Comment by sirocchj** [comment]
I think this is good work and the direction is correct.

However, please remember:
1. AFAIK promotional prices (to drive `isSale` flag) and clearance prices (`isClearance` flag) are emitted by `mw-promotions` and `mw-prices` (respectively) but *at the sku level* (yes, the avro of both talks about `product_id` but I suspect that's just not right and we should fix them /cc @dollyds5a)
2. the product stream you're planning on streaming from (i.e. https://github.com/saksdirect/mw-data-processor/pull/15/files#diff-0ad8bc9059b08a2c3be2ad542073dc52R30) can either be
  a. `mw-catalog`'s final topic (in which case it will contain a product with an `array<Sku>` and you will need to `flatMap` and emit each of those skus in another topic to join with promotion stream), _or_
  b. the sku-level one (which we'd need to expose to you in `mw-catalog` /cc @saksdirect/phoenix ), in which case you'd be able to join straight (like you're planning on/doing now).

Either way, the point I'm trying to make is that the joins are happening at the sku level, while you need to set `isSale`/`isClearance` at the parent product level, which means you'll need to extract the id of the product (in case 2.a. in your `flatMap` you can compose your payload as you wish and therefore you can put the parent id in the value there, in case 2.b. you'll have it in the value contained in the sku topic and you'll need to preserve it).

Once you join, you'll have all the info you need - keyed by sku id - i.e. is this sku on sale/clearance and from/to when and what's the product id it belongs to...

At that stage you then re-key by product id and join with the "target" topic for `mw-catalog` (the product w/ `set<sku>` and flick `isSale` on iff at least one of the skus has the flag on. Switching off needs care w.r.t time, as discussed...

Happy to walk through more, if needed

**Comment by xayang** [comment]
The reason why I use product_id as join key, is based on isSale as product level attribute.   My understanding is dynamic catalogue  will be used for website product array. One product maybe has a bunch of different sku items which could construct an array. If any one of these items has sale price, we can consider this product is on sale. In website product array, we can show this product as on sale. 

If we would have other consideration and prefer to make isSale attribute to sku level attribute,  I could change code and make sku_id as join key,  and then transfer sku level isSale attribute to product level if any sku item in this product has onSale property.

**Comment by sirocchj** [comment]
I’m not suggesting isSale is an attribute at sku level. I am saying that - despite being called `product_id` In the simple promos topic (and in the price topic!) - that is a sku id. Hence the rest: are you expecting to consume final products (in which case you’ll have to “unpack” the skus to join and later regroup) or are you expecting to join with sku level info? Judging by your comment I’d say you thought you were joining already at product level, but you aren’t.

**Comment by xayang** [comment]
After checking current mw-catalog, mw-promotion and mw-pricing code, I understand your meaning. Both mw-promotion and mw-pricing items are at the sku level. The  product_id in PriceValue is actually assigned to sku's SKN_NO.  mw-catalog sink topic is product stream but including sku items array. We need to adjust code according to the real source streams.

**Pull request closed without merging**
